# Generated by Django 2.2.5 on 2021-10-25 16:42

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical_word_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artical_index', models.IntegerField(default=0)),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artical_word_num_nosw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artical_index', models.IntegerField(default=0)),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_index', models.IntegerField(default=0)),
                ('Title', models.TextField(default='')),
                ('Context', models.TextField(default='')),
                ('Sentences_num', models.IntegerField(default=0)),
                ('Words_num', models.IntegerField(default=0)),
                ('Chars_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Artical_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Artical_index', models.IntegerField(default=0)),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Artical_nosw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Artical_index', models.IntegerField(default=0)),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Index', server.models.ListField()),
            ],
        ),
        migrations.CreateModel(
            name='Word_nosw_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word_stem_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(default='')),
                ('Counts', models.IntegerField(default=0)),
            ],
        ),
    ]
